// docs/.vuepress/components/publications.vue

<template>
    <div>
        <div v-for="item in pubs">
            <h3 class="title">{{item.csljson.title}} <Badge :text="csltype(item.data.itemType)" :type="csltip(csltype(item.data.itemType))"/></h3>
            <span v-for="author in item.csljson.author">{{author.given}} {{author.family}}, </span>
            <a v-if="getfields(item.data.extra).pdf" :href="getfields(item.data.extra).pdf">PDF</a> <a v-if="item.csljson.DOI" :href="item.csljson.DOI">DOI</a> 
            <a v-if="item.csljson.URL" :href="item.csljson.URL">Website</a> 
            <a v-if="getfields(item.data.extra).github" :href="getfields(item.data.extra).github">Code</a> 
            <a :href="exportbib(item.key, 'bibtex')">Bibtex</a> 
            <a :href="exportbib(item.key, 'csljson')">CSL-JSON</a> 
            <a v-if="item.csljson.DOI" :href="item.csljson.DOI">DOI</a>
        </div>
    </div>
</template>
<script>
const axios = require('axios')
// const cite = require('citation-js')

export default {
  data () {
      return {
          pubs: [],
          api_base: "https://api.zotero.org/users/"
      }
  },
  props: [
      'zotero_id'
  ],
  mounted() {
    var request_url = `${this.api_base}/${this.zotero_id}/publications/items?format=json&include=data,csljson&sort=date&limit=100`
    axios.get(request_url)
    .then(response => {
       this.pubs = response.data
    })
    .catch(error => {
        console.log(error);
    })
  },
  methods: {
    exportbib: function (key, format) {
      return `${this.api_base}/${this.zotero_id}/publications/items/${key}?format=${format}`
    },
    csltype: function (type) {
        switch(type) {
            case "conferencePaper":
                return "conference"
            case "journalArticle":
                return "journal"
            case "document":
                return "dataset"
            default:
                return type
            } 
    },
    csltip: function (type) {
        switch(type) {
            case "conference":
                return "warn"
            case "journal":
                return "error"
            case "data":
                return "info"
            default:
                return "info"
            } 
    },
    getfields: function (extra) {
        // code from https://github.com/zotero/zotero/blob/cbfa4be437fbe0451795a9a865ed163fa7cc2376/chrome/content/zotero/xpcom/cite.js
        
        var fields = {}
		var ex = extra.replace(/^([A-Za-z \-]+)(:\s*.+)/gm, function (_, field, value) {
            var field = field.toLowerCase().replace(/ /g, '-');
            return fields[field]= value.slice(2);
        });
        return fields;
    }
  }
}
</script>

<style>
.title {
    margin-bottom: 0px;
}
.csl-bib-body {
    line-height: 2; 
    padding-left: 0em!important; 
    text-indent: 0em!important;
}
</style>

// src/sections/Publications.tsx
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"

const ZOTERO_USER = "6408178"
const API_BASE = `https://api.zotero.org/users/${ZOTERO_USER}/publications/items`

type Author = { given?: string; family?: string }
type CSL = {
  title?: string
  author?: Author[]
  "container-title"?: string
  URL?: string
  DOI?: string
  issued?: { "date-parts"?: number[][] }
}
type ZoteroItem = {
  key: string
  csljson: CSL
  data: { date?: string; extra?: string; itemType?: string }
}

function parseExtra(extra?: string): Record<string, string> {
  const fields: Record<string, string> = {}
  if (!extra) return fields
  extra.replace(/^([A-Za-z \-]+)(:\s*.+)/gm, (_m, field: string, value: string) => {
    fields[field.toLowerCase().replace(/ /g, "-")] = value.slice(2).trim()
    return ""
  })
  return fields
}

function exportbib(key: string, format: "bibtex" | "csljson") {
  return `${API_BASE}/${key}?format=${format}`
}

function PubItem({ item }: { item: ZoteroItem }) {
  const csl = item.csljson
  const extra = parseExtra(item.data.extra)
  const authors = csl.author ?? []
  const venue = csl["container-title"]
  const date = item.data.date ?? csl.issued?.["date-parts"]?.[0]?.[0] ?? ""

  return (
    <article className="border-2 border-border rounded-base p-4 bg-secondary-background shadow-shadow">
      <h4 className="font-serif font-normal text-xl leading-snug">{csl.title}</h4>
      <p className="text-sm mt-1 opacity-90">
        {authors
          .map((a) => `${a.given ?? ""} ${a.family ?? ""}`.trim())
          .join(", ")}
      </p>
      {(venue || date) && (
        <p className="text-sm italic mt-1">
          {venue}
          {venue && date ? ", " : ""}
          {date}
        </p>
      )}
      <div className="flex flex-wrap gap-2 mt-3">
        {extra.pdf && (
          <Button variant="neutral" size="sm" asChild>
            <a href={extra.pdf} target="_blank" rel="noreferrer">
              PDF
            </a>
          </Button>
        )}
        {csl.URL && (
          <Button variant="neutral" size="sm" asChild>
            <a href={csl.URL} target="_blank" rel="noreferrer">
              Website
            </a>
          </Button>
        )}
        {extra.github && (
          <Button variant="neutral" size="sm" asChild>
            <a href={extra.github} target="_blank" rel="noreferrer">
              Code
            </a>
          </Button>
        )}
        {csl.DOI && (
          <Button variant="neutral" size="sm" asChild>
            <a
              href={`https://dx.doi.org/${csl.DOI}`}
              target="_blank"
              rel="noreferrer"
            >
              DOI
            </a>
          </Button>
        )}
        <Button variant="neutral" size="sm" asChild>
          <a href={exportbib(item.key, "bibtex")} target="_blank" rel="noreferrer">
            BibTeX
          </a>
        </Button>
        <Button variant="neutral" size="sm" asChild>
          <a href={exportbib(item.key, "csljson")} target="_blank" rel="noreferrer">
            JSON
          </a>
        </Button>
      </div>
    </article>
  )
}

function PubList({ filter, label }: { filter: string; label: string }) {
  const [items, setItems] = useState<ZoteroItem[] | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const url = `${API_BASE}?format=json&include=data,csljson&sort=date&limit=100&itemType=${filter}`
    fetch(url)
      .then(async (r) => {
        if (!r.ok) throw new Error(`Zotero API ${r.status}`)
        return (await r.json()) as ZoteroItem[]
      })
      .then(setItems)
      .catch((e) => setError(String(e)))
  }, [filter])

  if (error) {
    return (
      <p className="text-sm text-foreground/70">
        Could not load {label.toLowerCase()}: {error}
      </p>
    )
  }
  if (!items) {
    return (
      <ul className="space-y-3">
        {[0, 1, 2].map((i) => (
          <li
            key={i}
            className="border-2 border-border rounded-base p-4 bg-secondary-background animate-pulse h-24"
          />
        ))}
      </ul>
    )
  }
  if (items.length === 0) {
    return <p className="text-sm">No {label.toLowerCase()} listed.</p>
  }
  return (
    <ul className="space-y-3">
      {items.map((it) => (
        <li key={it.key}>
          <PubItem item={it} />
        </li>
      ))}
    </ul>
  )
}

export default function Publications() {
  return (
    <section id="publications" className="scroll-mt-20">
      <h2 className="font-heading text-3xl sm:text-4xl mb-6 inline-block bg-main text-main-foreground border-2 border-border rounded-base px-3 py-1 shadow-shadow">
        Publications
      </h2>
      <div className="flex flex-wrap gap-2 mb-6">
        <Button variant="neutral" size="sm" asChild>
          <a
            href="https://scholar.google.com/citations?user=7HsSdqwAAAAJ&hl=en"
            target="_blank"
            rel="noreferrer"
          >
            Google Scholar
          </a>
        </Button>
        <Button variant="neutral" size="sm" asChild>
          <a href="https://www.zotero.org/faroit" target="_blank" rel="noreferrer">
            Zotero
          </a>
        </Button>
      </div>

      <h3 className="font-heading text-4xl sm:text-5xl mb-3">Peer-reviewed journals</h3>
      <PubList filter="journalArticle" label="Journal articles" />

      <h3 className="font-heading text-4xl sm:text-5xl mt-10 mb-3">
        Peer-reviewed conferences
      </h3>
      <PubList filter="conferencePaper" label="Conference papers" />
    </section>
  )
}
